<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usery', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//render form cara 1
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
//render form cara 2 
//echo $this->formCollection($form);
echo $this->form()->closeTag();

