<h1 class="page-header">User</h1>
<?php if(!empty($this->users3)) : ?>
    <?php foreach ($this->users3 as $row) : ?>
        <?=$row->user_name . PHP_EOL?>
    <?php endforeach; ?>
<?php endif; ?>
<br />
---
<br />

<?php if(!empty($this->users2)) : ?>
    <?php foreach ($this->users2 as $row) : ?>
        <?=$row->user_name . PHP_EOL?>
    <?php endforeach; ?>
<?php endif; ?>

    Page index user.<br />

<?php if(!empty($this->users)) : ?>
    <?php foreach ($this->users as $row) : ?>
        <?=$row->user_name . PHP_EOL?>
    <?php endforeach; ?>
<?php else : ?>
    No Data
<?php endif; ?>

